/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lcdrpl.gui.lefttab;

import java.awt.Color;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author Lenovo2
 */
public class TabButton extends lcdrpl.gui.ImagePanel {
    private LeftTabPanel parent;
    private ImageIcon normalIcon;
    private ImageIcon hoverIcon;
    private ImageIcon pressedIcon;
    private Color normalColor = new Color(169, 165, 186);
    private Color hoverColor = new Color(255, 255, 255);
    private Color pressedColor = new Color(135,142,142);
    private boolean mouseEntered = false;
    private boolean mousePressed = false;
    private java.awt.event.MouseAdapter onClick = null;
    /**
     * Creates new form TabButton
     */
    public TabButton() {
        initComponents();
        //refreshButtonState();
    }
    
    public void setParent(LeftTabPanel parent){
        this.parent = parent;
    }
    
    public void setText(String text){
        detailLabel.setText(text);
    }
    
    public String getText(){
        return detailLabel.getText();
    }
    
    public void setNormalIcon(String iconName){
        normalIcon = new javax.swing.ImageIcon(getClass().getResource("/lcdrpl/images/" + iconName));
        refreshButtonStateLater();
    }
    public void setHoverIcon(String iconName){
        hoverIcon = new javax.swing.ImageIcon(getClass().getResource("/lcdrpl/images/" + iconName));
        refreshButtonStateLater();
    }
    public void setPressedIcon(String iconName){
        pressedIcon = new javax.swing.ImageIcon(getClass().getResource("/lcdrpl/images/" + iconName));
        refreshButtonStateLater();
    }
    
    public void setClickListener(java.awt.event.MouseAdapter adapter){
        onClick = adapter;
    }
    
    public void setDetailVisible(boolean visible){
        detailLabel.setVisible(visible);
    }
    
    public void refreshButtonStateLater(){
        
        javax.swing.SwingUtilities.invokeLater(new Runnable(){
            @Override
            public void run(){
                refreshButtonState();
            }
        });
    }
    
    public void refreshButtonState(){
        if(mouseEntered){
            if(mousePressed){
                iconLabel.setIcon(pressedIcon);
                detailLabel.setForeground(pressedColor);
            }else{
                iconLabel.setIcon(hoverIcon);
                detailLabel.setForeground(hoverColor);
            }
        }else{
            iconLabel.setIcon(normalIcon);
            detailLabel.setForeground(normalColor);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconLabel = new lcdrpl.gui.ImageLabel();
        detailLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0, 0));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        setOpaque(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        iconLabel.setPreferredSize(new java.awt.Dimension(32, 32));
        add(iconLabel);

        detailLabel.setForeground(java.awt.SystemColor.controlLtHighlight);
        detailLabel.setText("jLabel2");
        add(detailLabel);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        mouseEntered = true;
        //System.out.println("Mouse Entered");
        refreshButtonState();
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        mouseEntered = false;
        //System.out.println("Mouse Exited");
        refreshButtonState();
    }//GEN-LAST:event_formMouseExited

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        mousePressed = true;
        //System.out.println("Mouse Pressed");
        refreshButtonState();
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        mousePressed = false;
        //System.out.println("Mouse Released");
        refreshButtonState();
        if(mouseEntered){
            if(parent != null) parent.onClick(this);
            if(onClick != null) onClick.mouseReleased(evt);
        }
    }//GEN-LAST:event_formMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel detailLabel;
    private lcdrpl.gui.ImageLabel iconLabel;
    // End of variables declaration//GEN-END:variables
}
